# Generated by Django 5.2.17 on 2026-09-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('cd_down', models.AutoField(db_column='cd_down', primary_key=True, serialize=False)),
                ('nm_down', models.CharField(db_column='nm_down', max_length=255)),
                ('arq_down', models.CharField(db_column='arq_down', max_length=255, unique=True)),
                ('data_down', models.DateTimeField(db_column='data_down')),
            ],
            options={
                'db_table': 'tb_downloads',
                'ordering': ['-data_down'],
                'managed': False,
            },
        ),
    ]
